function [Gbar] = G_matrix_bar(X,q)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
g = 9.81;

phi = q(4);
theta = q(5);
psi = q(6);

m1 = X(1);


% Gbar = [                                                                                  -(g*m1*sin(theta))/(cos(theta)^2 + sin(theta)^2);...
%     (g*m1*cos(theta)*sin(phi))/(cos(phi)^2*cos(theta)^2 + cos(phi)^2*sin(theta)^2 + cos(theta)^2*sin(phi)^2 + sin(phi)^2*sin(theta)^2);...
%     (g*m1*cos(phi)*cos(theta))/(cos(phi)^2*cos(theta)^2 + cos(phi)^2*sin(theta)^2 + cos(theta)^2*sin(phi)^2 + sin(phi)^2*sin(theta)^2);...
%     0;...
%     0;...
%     0];

Gbar = [    0;...
    0;...
    g*m1;...
    0;...
    0;...
    0];


end

